config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "welcome/index"
  get "picture/index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pictures do
    resources :comments
  end
  resources :users
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  # This method associates the attribute ":avatar" with a file attachment
  has_attached_file :image, styles: {
    thumb: "100x100>",
    square: "200x200#",
    medium: "300x200#",
    large: "500x340#"
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

    def configure_permitted_parameters
      added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @picture = Picture.find(params[:picture_id])
  end

  def index
    @picture = Picture.find(params[:picture_id])
  end

  def create
    @picture = Picture.find(params[:picture_id])
    @comment = @picture.comments.create(comment_params.merge(author: current_user.username, user_id: current_user.id))
    redirect_to picture_comments_url
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_back(fallback_location: picture_comments_url)
  end

  def edit
    @picture = Picture.find(params[:picture_id])
    @comment = @picture.comments.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params.merge(author: current_user.username, user_id: current_user.id))
    redirect_to picture_comments_url
  end

  def comment_params
    params.require(:comment).permit(:author, :body, :comment_id, :user_id)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def new
    @picture = Picture.new
  end

  def show
  end

  def create
    @picture = Picture.create(picture_params.merge(user_id: current_user.id))
    redirect_to user_url(current_user.id)
  end

  def destroy
    @picture = Picture.find(params[:id])
    if @picture.present?
      @picture.destroy
    end
    redirect_back(fallback_location: user_url)
  end

  def picture_params
    params.require(:picture).permit(:image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/edit.html.erb
<%= form_with(model: [@picture, @comment], local: true) do |form| %>
  <p>
    <%= form.label :body, "Edit Comment" %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit :Confirm %>
  </p>
<% end %>

app/views/comments/index.html.erb
<% if user_signed_in? %>
  <%= image_tag @picture.image.url(:large)  %>
  <% @picture.comments.each do |comment| %>
  <div>
    <%= comment.body %></br>
    <%= button_to('Delete', picture_comment_path(comment.picture_id, comment.id), {method: :delete}) %>
    <%= button_to('Edit Comment', edit_picture_comment_path(comment.picture_id, comment.id), {method: :get}) %>
  </div>
  <% end %>
<% end %>

app/views/comments/new.html.erb
<%= form_with(model: [ @picture, @picture.comments.build ], local: true) do |form| %>
<p>
  <%= form.label :body %><br>
  <%= form.text_area :body %>
</p>
<p>
  <%= form.submit :Comment %>
</p>
<% end %>

app/views/layouts/_profile_button.html.erb
<% if user_signed_in? %>
  <%= button_to('Profile', user_path(current_user.id), {method: :get, id: 'banner_btn'}) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Picture Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id='banner'>
      <div id='banner_button'>
        <%= render 'layouts/profile_button' %>
        <%= render 'users/show_all_users' %>
      </div>
      <div id='banner_text'>
        <h1 id='welcome_header'>Picture Rails</h1>
      </div>
      <div id='banner_button'>
        <%= render 'welcome/sign_up' %>
        <%= render 'welcome/log_in_and_out' %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pictures/new.html.erb
<%= form_with scope: :picture, url: pictures_path, local: true do |form| %>
  <p>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </p>
  <p>
    <%= form.submit 'Post' %>
  </p>
<% end %>

app/views/users/_show_all_users.html.erb
<% if user_signed_in? %>
  <%= button_to('All Users', users_path, method: :get, id: 'banner_btn') %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= button_to("#{user.username}", user_path(user), {method: :get}) %>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile Page</h1>
<% if user_signed_in? %>
<h6>Logged in as: <%=current_user.username%></h6>
<% end %>
<div id="picture_deck">
  <div id="album_div">
    <% @user.pictures.reverse.each do |picture| %>
      <div id="image_div">
        <%= link_to image_tag(picture.image.url(:medium)), picture_comments_path(picture) %>
        <% if @user == current_user %>
          <%= button_to('Delete', picture_path(picture), {method: :delete}) %>
        <% end %>
        <%= button_to('Comment', new_picture_comment_path(picture), {method: :get}) %>
      </div>
    <% end %>
  </div>
  <% if @user == current_user %>
    <div id="upload_button">
      <%= button_to('Upload Picture', new_picture_path, {method: :get}) %>
    </div>
  <% end %>
</div>

app/views/welcome/_log_in_and_out.html.erb
<% if user_signed_in? %>
  <%= button_to('Logout', destroy_user_session_path, method: :delete, id: 'banner_btn') %>
<% else %>
  <%= button_to('Login', new_user_session_path, id: 'banner_btn')  %>
<% end %>

app/views/welcome/_sign_up.html.erb
<% if user_signed_in? %>
  <%= button_to('Edit', edit_user_registration_path, {method: :get, id: 'banner_btn'}) %>
<% else %>
  <%= button_to('Register', new_user_registration_path, {method: :get, id: 'banner_btn'})  %>
<% end %>

app/views/welcome/_user_profile_page.html.erb
<h1 id="welcome_header"><%= current_user.username %>'s Profile Page</h1>
<div id="picture_deck">
  <div id="album_div">
    <% current_user.pictures.each do |picture| %>
      <div id="image_div">
        <%= image_tag picture.image.url(:medium)  %>
      </div>
    <% end %>
  </div>
  <div id="upload_button">
    <%= button_to('Upload Picture', new_picture_path, {method: :get}) %>
  </div>
</div>

app/views/welcome/index.html.erb
<body>
</body